# Render Blueprint (Infrastructure-as-Code)
# Learn more: https://render.com/docs/blueprint-spec
services:
  - type: web
    name: habition-api-gateway
    env: docker
    dockerfilePath: ./backend/ApiGateway/Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    branch: deploy
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: FRONTEND_URLS
        sync: false
