# Server Port
server.port=${PORT:8761}

# Application Name
spring.application.name=EUREKA-SERVER

# Disable self-registration
eureka.client.register-with-eureka=false

# Disable fetching registry
eureka.client.fetch-registry=false

# Eureka Dashboard URL
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

