# Server Port
server.port=8761

# Application Name
spring.application.name=EUREKA-SERVER

# Disable self-registration
eureka.client.register-with-eureka=false

# Disable fetching registry
eureka.client.fetch-registry=false

# Eureka Dashboard URL
eureka.instance.hostname=localhost


